theme: jekyll-theme-minimal
title: Office Auto Installer
description: Easy Microsoft Office installation for everyone
url: https://njvanas.github.io/Office-Auto-Install
baseurl: /Office-Auto-Install
plugins:
  - jekyll-sitemap
  - jekyll-feed