#Requires -Version 5.1
<#
.SYNOPSIS
    Single-command bootstrap: downloads the right scripts from GitHub and runs the Microsoft 365 Apps installer.

.DESCRIPTION
    One liner for everyone:
    - Default: graphical installer for home and business users (same experience as always).
    - Optional: text-only wizard or IT silent deploy. Downloads M365AppsCore.ps1 + your chosen installer script.
      ODT (setup.exe) comes from Microsoft at install time; configuration XML is generated by those scripts.

    Set OFFICE_AUTO_INSTALL_MODE before irm | iex:
      gui     — WPF installer (default)
      console — prompts in the terminal
      deploy  — runs Deploy-Microsoft365Apps.ps1 (downloads ODT; all deploy XML is generated in code)

    Fork: OFFICE_AUTO_INSTALL_REPO, OFFICE_AUTO_INSTALL_BRANCH

.EXAMPLE
    # End user — graphical installer (default)
    irm "https://njvanas.github.io/Office-Auto-Install/office.ps1" | iex

.EXAMPLE
    # Same as default; explicit mode
    $env:OFFICE_AUTO_INSTALL_MODE = "gui"
    irm "https://njvanas.github.io/Office-Auto-Install/office.ps1" | iex

.EXAMPLE
    # Text-only wizard
    $env:OFFICE_AUTO_INSTALL_MODE = "console"
    irm "https://njvanas.github.io/Office-Auto-Install/office.ps1" | iex

.EXAMPLE
    # IT — AVD / shared PC (silent ODT deploy; run PowerShell as Administrator)
    $env:OFFICE_AUTO_INSTALL_MODE = "deploy"
    $env:OFFICE_AUTO_INSTALL_RETAIL_PROFILE = "EnterpriseVDI"
    $env:OFFICE_AUTO_INSTALL_LANGUAGE = "en-us"
    irm "https://njvanas.github.io/Office-Auto-Install/office.ps1" | iex

.NOTES
    Legacy: OFFICE_AUTO_INSTALL_USE_CONSOLE=1 still selects console mode if MODE is not set.
#>

$ErrorActionPreference = "Stop"

# Prefer not relying on Set-ExecutionPolicy (GPO may block it). Child process uses -ExecutionPolicy Bypass -File.
try {
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force -ErrorAction SilentlyContinue
} catch { }

$DefaultRepo = "njvanas/Office-Auto-Install"
$DefaultBranch = "main"

if (-not ([Net.ServicePointManager]::SecurityProtocol -band [Net.SecurityProtocolType]::Tls12)) {
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    } catch { }
}

$repo = if ($env:OFFICE_AUTO_INSTALL_REPO) { $env:OFFICE_AUTO_INSTALL_REPO.Trim() } else { $DefaultRepo }
$branch = if ($env:OFFICE_AUTO_INSTALL_BRANCH) { $env:OFFICE_AUTO_INSTALL_BRANCH.Trim() } else { $DefaultBranch }
$base = "https://raw.githubusercontent.com/$repo/$branch"

# Mode: gui | console | deploy (backward compat: USE_CONSOLE=1 → console)
$mode = if ($env:OFFICE_AUTO_INSTALL_MODE) {
    $env:OFFICE_AUTO_INSTALL_MODE.Trim().ToLowerInvariant()
} elseif ($env:OFFICE_AUTO_INSTALL_USE_CONSOLE -eq "1") {
    'console'
} else {
    'gui'
}

if ($mode -notin @('gui', 'console', 'deploy')) {
    Write-Host " ERROR: OFFICE_AUTO_INSTALL_MODE must be gui, console, or deploy (got '$mode')." -ForegroundColor Red
    exit 1
}

$scriptFile = switch ($mode) {
    'gui' { 'Install-Office-GUI-WPF.ps1' }
    'console' { 'Install-Office.ps1' }
    'deploy' { 'Deploy-Microsoft365Apps.ps1' }
}

$safeRepo = ($repo -replace '/', '_')
$stage = Join-Path $env:TEMP "OfficeAutoInstall\$safeRepo\$branch"
New-Item -ItemType Directory -Path $stage -Force | Out-Null

$corePath = Join-Path $stage 'M365AppsCore.ps1'
$payloadPath = Join-Path $stage $scriptFile

Write-Host ""
Write-Host " =================================================================" -ForegroundColor Cyan
Write-Host "  Microsoft 365 Apps - Office Auto Install" -ForegroundColor White
if ($mode -eq 'gui') {
    Write-Host "  Profile: Standard (graphical installer)" -ForegroundColor Gray
    Write-Host "  Tip: Run PowerShell as Administrator when prompted." -ForegroundColor DarkGray
} elseif ($mode -eq 'console') {
    Write-Host "  Profile: Step-by-step (terminal)" -ForegroundColor Gray
} else {
    Write-Host "  Profile: IT - silent deploy (ODT)" -ForegroundColor Yellow
    Write-Host "  Requires: Administrator PowerShell" -ForegroundColor DarkGray
}
Write-Host "  Source: $repo @ $branch" -ForegroundColor DarkGray
Write-Host " =================================================================" -ForegroundColor Cyan
Write-Host ""

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if ($mode -eq 'deploy') {
    if (-not $isAdmin) {
        Write-Host " Deploy mode must run elevated. Open PowerShell as Administrator and run the same command." -ForegroundColor Red
        Write-Host ""
        if ($Host.Name -eq "ConsoleHost") {
            try { $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") } catch { Read-Host "Press Enter to exit" }
        }
        exit 1
    }
} elseif (-not $isAdmin) {
    Write-Host " Administrator rights are required to install Office." -ForegroundColor Yellow
    Write-Host " Open Terminal or PowerShell as Administrator, then run this command again." -ForegroundColor Yellow
    Write-Host ""
}

function Get-OaiWebFile {
    param([string]$Uri, [string]$OutFile)
    Invoke-WebRequest -Uri $Uri -OutFile $OutFile -UseBasicParsing -MaximumRedirection 5 -TimeoutSec 120
}

function Get-OaiWindowsPowerShellExe {
    $p = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    if (Test-Path -LiteralPath $p) { return $p }
    return 'powershell.exe'
}

function Start-OaiScriptWithExecutionBypass {
    <#
    .SYNOPSIS
        Runs a downloaded .ps1 in a child Windows PowerShell with -ExecutionPolicy Bypass (works when the parent session cannot run scripts).
    #>
    param(
        [Parameter(Mandatory)]
        [string]$FilePath,
        [string[]]$ArgumentList = @(),
        [switch]$HideHostWindow
    )
    $exe = Get-OaiWindowsPowerShellExe
    $args = [System.Collections.Generic.List[string]]::new()
    [void]$args.Add('-NoProfile')
    [void]$args.Add('-ExecutionPolicy')
    [void]$args.Add('Bypass')
    [void]$args.Add('-File')
    [void]$args.Add($FilePath)
    foreach ($a in $ArgumentList) {
        [void]$args.Add($a)
    }
    if ($HideHostWindow) {
        $p = Start-Process -FilePath $exe -ArgumentList $args -Wait -PassThru -WindowStyle Hidden
    } else {
        $p = Start-Process -FilePath $exe -ArgumentList $args -Wait -PassThru -NoNewWindow
    }
    return $p.ExitCode
}

try {
    Get-OaiWebFile -Uri "$base/M365AppsCore.ps1" -OutFile $corePath

    if ($mode -in 'gui', 'console') {
        Get-OaiWebFile -Uri "$base/$scriptFile" -OutFile $payloadPath
    } else {
        Get-OaiWebFile -Uri "$base/Deploy-Microsoft365Apps.ps1" -OutFile $payloadPath
    }
} catch {
    Write-Host " ERROR: Download from GitHub failed." -ForegroundColor Red
    Write-Host " $($_.Exception.Message)" -ForegroundColor Yellow
    Write-Host ""
    Write-Host " Check repo/branch (OFFICE_AUTO_INSTALL_REPO / OFFICE_AUTO_INSTALL_BRANCH) and network." -ForegroundColor Gray
    if ($Host.Name -eq "ConsoleHost") {
        try { $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown") } catch { Read-Host "Press Enter to exit" }
    }
    exit 1
}

if (-not (Test-Path -LiteralPath $corePath) -or -not (Test-Path -LiteralPath $payloadPath)) {
    Write-Host " ERROR: Required files are missing after download." -ForegroundColor Red
    exit 1
}

try {
    Unblock-File -LiteralPath $corePath -ErrorAction SilentlyContinue
    Unblock-File -LiteralPath $payloadPath -ErrorAction SilentlyContinue
} catch { }

Write-Host " Files ready. Starting..." -ForegroundColor Green
Write-Host ""

if ($mode -in 'gui', 'console') {
    $hide = ($mode -eq 'gui')
    $code = Start-OaiScriptWithExecutionBypass -FilePath $payloadPath -HideHostWindow:$hide
    exit $code
}

. $corePath

# --- Deploy mode: map environment to Deploy-Microsoft365Apps.ps1 parameters ---
$uninstall = ($env:OFFICE_AUTO_INSTALL_UNINSTALL -eq '1')
$lang = if ($env:OFFICE_AUTO_INSTALL_LANGUAGE) { $env:OFFICE_AUTO_INSTALL_LANGUAGE.Trim() } elseif ($env:OFFICE_AUTO_INSTALL_LANGUAGEID) { $env:OFFICE_AUTO_INSTALL_LANGUAGEID.Trim() } else { 'en-us' }

$retailProfile = $null
if ($env:OFFICE_AUTO_INSTALL_RETAIL_PROFILE) {
    $retailProfile = $env:OFFICE_AUTO_INSTALL_RETAIL_PROFILE.Trim()
}
$bundleName = $null
if ($env:OFFICE_AUTO_INSTALL_BUNDLE) {
    $bundleName = $env:OFFICE_AUTO_INSTALL_BUNDLE.Trim()
}
# Legacy: OFFICE_AUTO_INSTALL_PRESET (old O365*.xml names or Visio+Project bundle names)
if ($env:OFFICE_AUTO_INSTALL_PRESET) {
    $legacy = $env:OFFICE_AUTO_INSTALL_PRESET.Trim()
    $mapped = Resolve-M365AppsLegacyO365PresetNameToRetailProfile -Name $legacy
    if ($mapped) {
        $retailProfile = $mapped
    } elseif ($legacy -match 'VisioProject') {
        $bundleName = $legacy
    }
}

$deployArgs = @{
    LanguageId = $lang
}
if ($env:OFFICE_AUTO_INSTALL_CHANNEL) {
    $deployArgs.Channel = $env:OFFICE_AUTO_INSTALL_CHANNEL.Trim()
}
if ($env:OFFICE_AUTO_INSTALL_ARCH -match '^(32|64)$') {
    $deployArgs.OfficeClientEdition = $env:OFFICE_AUTO_INSTALL_ARCH
}
if ($env:OFFICE_AUTO_INSTALL_WORKING_DIRECTORY) {
    $deployArgs.WorkingDirectory = $env:OFFICE_AUTO_INSTALL_WORKING_DIRECTORY.Trim()
}
if ($env:OFFICE_AUTO_INSTALL_SKIP_PREREQ -eq '1') {
    $deployArgs.SkipPrerequisiteTest = $true
}
if ($env:OFFICE_AUTO_INSTALL_SKIP_ADMIN -eq '1') {
    $deployArgs.SkipAdministratorCheck = $true
}

$excludeAppsFromEnv = $null
if ($env:OFFICE_AUTO_INSTALL_EXCLUDE_APPS) {
    $ea = @($env:OFFICE_AUTO_INSTALL_EXCLUDE_APPS -split ',') | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    if ($ea.Count -gt 0) { $excludeAppsFromEnv = $ea }
}

$deployArgList = [System.Collections.Generic.List[string]]::new()
if ($uninstall) {
    Write-Host " Running uninstall (Microsoft 365 Apps removal)..." -ForegroundColor Yellow
    [void]$deployArgList.Add('-Uninstall')
} elseif ($bundleName) {
    Write-Host " Bundle: $bundleName  |  Language: $lang" -ForegroundColor Gray
    if ($excludeAppsFromEnv) { $deployArgs.ExcludeApp = $excludeAppsFromEnv }
    [void]$deployArgList.Add('-Bundle')
    [void]$deployArgList.Add($bundleName)
} else {
    if (-not $retailProfile) { $retailProfile = 'EnterprisePhysical' }
    Write-Host " Retail profile: $retailProfile  |  Language: $lang" -ForegroundColor Gray
    if ($excludeAppsFromEnv) { $deployArgs.ExcludeApp = $excludeAppsFromEnv }
    [void]$deployArgList.Add('-RetailProfile')
    [void]$deployArgList.Add($retailProfile)
}
[void]$deployArgList.Add('-LanguageId')
[void]$deployArgList.Add($lang)
if ($deployArgs.Channel) {
    [void]$deployArgList.Add('-Channel')
    [void]$deployArgList.Add($deployArgs.Channel)
}
if ($deployArgs.OfficeClientEdition) {
    [void]$deployArgList.Add('-OfficeClientEdition')
    [void]$deployArgList.Add($deployArgs.OfficeClientEdition)
}
if ($deployArgs.WorkingDirectory) {
    [void]$deployArgList.Add('-WorkingDirectory')
    [void]$deployArgList.Add($deployArgs.WorkingDirectory)
}
if ($deployArgs.SkipPrerequisiteTest) { [void]$deployArgList.Add('-SkipPrerequisiteTest') }
if ($deployArgs.SkipAdministratorCheck) { [void]$deployArgList.Add('-SkipAdministratorCheck') }
if ($deployArgs.ExcludeApp) {
    foreach ($ex in @($deployArgs.ExcludeApp)) {
        if ($ex) {
            [void]$deployArgList.Add('-ExcludeApp')
            [void]$deployArgList.Add([string]$ex)
        }
    }
}

$exitCode = Start-OaiScriptWithExecutionBypass -FilePath $payloadPath -ArgumentList $deployArgList.ToArray()
exit $exitCode
